### ISSUE TITLE
Visão Geral

### ISSUE THREAD

**Issue by ferdinandocastilho** [ferdinandocastilho/selecao-cteds#2]

**Comment by ferdinandocastilho** [comment]
Definir Requisitos da Solução (o que irá fazer e como)
 Definir Tecnologia
 Definir time e Responsabilidades
 Documento de Arquitetura
 Protótipo

**Comment by RenatoNr** [comment]
Teste

**Comment by RenatoNr** [comment]
- [ ] Escopo
  -Epic - Módulos que compõem o projeto
  -Feature - Funcionalidades dentro dos módulos
  -User History - O que a feature vai fazer/resolver

**Comment by ferdinandocastilho** [comment]
### Requisitos do Sistema ### 
Desenvolver uma aplicação para o recrutamento do segundo oferecimento CTEDS da Universidade Politécnica de São Paulo.

A solução deverá incluir:

- Registro de Interesse do Candidato
- Abertura do formulário de informações quando o processo seletivo iniciar
- Identificação e extração dos campos de Escolaridade, Experiência Profissional e Trabalhos Voluntários do LinkedIn
- Triagem de requisitos automatizada baseada nas condições pré-estabelecidas pelo departamento de recrutamento da USP
- Teste Embutido de múltipla escolha, disserativo e compilável (para exames de desenvolvimento) e Nota
- Obtenção de resultados e emissão dos aprovados
- Cadastro de grade escolar, atividades e fóruns

**Comment by ferdinandocastilho** [comment]
### Tecnologia e Frameworks ### 

Quem se voluntaria? 🙋🙋‍♀️
_Clicar nos três pontinhos do comentário e selecionar "Editar"_

**Comment by ferdinandocastilho** [comment]
### Time e Responsabilidades ### 

Quem se voluntaria? 🙋🙋‍♀️
_Clicar nos três pontinhos do comentário e selecionar "Editar"_

**Comment by ferdinandocastilho** [comment]
### Documento de Arquitetura ### 

Quem se voluntaria? 🙋🙋‍♀️
_Clicar nos três pontinhos do comentário e selecionar "Editar"_

**Comment by ferdinandocastilho** [comment]
### Protótipo ### 

Quem se voluntaria? 🙋🙋‍♀️
_Clicar nos três pontinhos do comentário e selecionar "Editar"_

**Comment by RenatoNr** [comment]
Definido escopo geral do projeto
